width = 512
height = 256

[background]
type = "texture"
size = [212, 236]

[paper]
type = "slot"
position = [14, 23]

[ink]
type = "slot"
position = [14, 66]

[result]
type = "slot"
position = [14, 203]

[inventory]
type = "slots"
count = [3, 9]
position = [45, 155]

[selection]
type = "slots"
count = 9
position = [45, 213]

[canvas]
type = "texture"
size = [130, 130]
uv = [212, 0]
position = [58, 11]

[shadow]
type = "texture"
size = [130, 130]
uv = [342, 0]
position = [58, 11]

[up_normal]
type = "texture"
size = [11, 7]
uv = [11, 236]

[up_hover]
type = "texture"
size = [11, 7]
uv = [11, 243]

[down_normal]
type = "texture"
size = [11, 7]
uv = [0, 236]

[down_hover]
type = "texture"
size = [11, 7]
uv = [0, 243]

[output_normal]
type = "texture"
size = [12, 14]
uv = [66, 236]

[copy_normal]
type = "texture"
size = [12, 14]
uv = [78, 236]

[up]
type = "button"
size = [11, 7]
position = [16, 112]
tooltip = "sinocalligraphy.gui.button.up"
texture = "up_normal"
texture_hover = "up_hover"

[down]
type = "button"
size = [11, 7]
position = [16, 166]
tooltip = "sinocalligraphy.gui.button.down"
texture = "down_normal"
texture_hover = "down_hover"

[output]
type = "button"
size = [14, 14]
position = [190, 111]
texture = "output_normal"

[copy]
type = "button"
size = [14, 14]
position = [190, 127]
texture = "output_normal"
